import React, { useState, useEffect, useRef } from 'react';
import { 
  Activity, 
  ShieldAlert, 
  Network, 
  BarChart3, 
  Users, 
  FileKey,
  AlertTriangle,
  ArrowUpRight,
  TrendingUp,
  Search,
  Bell,
  ScanFace,
  CheckCircle,
  X,
  Lock,
  AlertOctagon,
  ExternalLink
} from 'lucide-react';
import { 
  AreaChart,
  Area,
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar
} from 'recharts';
import { motion, AnimatePresence } from 'framer-motion';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import ParticleBackground from './ParticleBackground';
import EntityInvestigation from './EntityInvestigation';

const API_URL = 'http://localhost:3001/api';
const WS_URL = 'ws://localhost:3001';

const App = () => {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [selectedBank, setSelectedBank] = useState(null);
  const [activeTab, setActiveTab] = useState('fraud'); 
  const [networkAnomalies, setNetworkAnomalies] = useState([]);
  const [creditProfile, setCreditProfile] = useState(null);
  const [currentUser, setCurrentUser] = useState(null);
  
  // Freeze Tracker State
  const [freezeSearchInput, setFreezeSearchInput] = useState('');
  const [freezeSearchResults, setFreezeSearchResults] = useState(null);
  const [isFreezeSearching, setIsFreezeSearching] = useState(false);
  const [hasSearched, setHasSearched] = useState(false);

  const handleFreezeSearch = async (e) => {
    e.preventDefault();
    if (!freezeSearchInput.trim()) return;
    
    setIsFreezeSearching(true);
    setHasSearched(true);
    setFreezeSearchResults(null);
    
    // Log audit action
    if (currentUser) {
       fetch(`${API_URL}/freeze-tracker/log`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ username: currentUser.username, query: freezeSearchInput })
       }).catch(err => console.error("Could not log search", err));
    }
    
    try {
      const res = await fetch(`${API_URL}/freeze-tracker/search`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: freezeSearchInput.trim() })
      });
      const data = await res.json();
      
      // Add fake delay for loading animation UX
      setTimeout(() => {
        if (data.success && data.data) {
          setFreezeSearchResults(data.data);
        } else {
          setFreezeSearchResults(null);
        }
        setIsFreezeSearching(false);
      }, 800);
    } catch (err) {
      console.error(err);
      setIsFreezeSearching(false);
    }
  };

  // Camera State for e-KYC
  const [cameraActive, setCameraActive] = useState(false);
  const [capturedImage, setCapturedImage] = useState(null);
  const videoRef = useRef(null);
  const canvasRef = useRef(null);
  const streamRef = useRef(null);

  // Toast State
  const [toasts, setToasts] = useState([]);

  // Compliance Logs State
  const defaultLogs = [
    { id: 'SAR-9901', type: 'Federal SAR Filing', entity: 'CryptoBridge Ltd', author: 'System API', time: 'Just Now', status: 'SUBMITTED', statusColor: 'high' },
    { id: 'CR-FBD-22', type: 'Credit Assessment (SHAP)', entity: 'CUST-88219', author: 'Automated Model', time: '2 Hrs Ago', status: 'ARCHIVED', statusColor: 'low' },
    { id: 'FR-AL-011', type: 'False Positive Log', entity: 'TXN-3910', author: 'johndoe@bank.internal', time: '4 Hrs Ago', status: 'TRAINING SET', statusColor: 'medium' }
  ];
  const [complianceLogs, setComplianceLogs] = useState(() => {
    const saved = localStorage.getItem('fraudApp_complianceLogs');
    try { return saved ? JSON.parse(saved) : defaultLogs; } 
    catch { return defaultLogs; }
  });

  useEffect(() => {
    localStorage.setItem('fraudApp_complianceLogs', JSON.stringify(complianceLogs));
  }, [complianceLogs]);
  const [selectedLogs, setSelectedLogs] = useState([]);

  const handleSelectAllLogs = (e) => {
    if (e.target.checked) {
      setSelectedLogs(complianceLogs.map(log => log.id));
    } else {
      setSelectedLogs([]);
    }
  };

  const handleSelectLog = (id) => {
    setSelectedLogs(prev => 
      prev.includes(id) ? prev.filter(logId => logId !== id) : [...prev, id]
    );
  };

  const handleDeleteSelectedLogs = () => {
    setComplianceLogs(prev => prev.filter(log => !selectedLogs.includes(log.id)));
    setSelectedLogs([]);
    addToast(`${selectedLogs.length} record(s) deleted successfully.`);
  };

  const handleExportCSV = () => {
    if (complianceLogs.length === 0) {
      addToast("No data to export.", 'warning');
      return;
    }
    
    const headers = ['Report ID', 'Type', 'Target Entity', 'Generated By', 'Timestamp', 'Status'];
    const csvRows = complianceLogs.map(log => 
      [log.id, log.type, log.entity, log.author, log.time, log.status].map(val => `"${val}"`).join(',')
    );
    const csvContent = [headers.join(','), ...csvRows].join('\n');
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', 'Compliance_Master_Log.csv');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    addToast("Exported to CSV! Your browser will open/save the file for Excel.", 'success');
  };

  const addToast = (message, type = 'success') => {
    const id = Date.now() + Math.random();
    setToasts(prev => [...prev, { id, message, type }]);
    setTimeout(() => {
      setToasts(prev => prev.filter(t => t.id !== id));
    }, 4000);
  };

  const [kycData, setKycData] = useState({
    customerName: '',
    accountNumber: '',
    bankName: '',
    ifscCode: '',
    aadhaarNumber: '',
    mobileNumber: '',
    address: ''
  });

  // Real-time telemetry state
  const [fraudTimelineData, setFraudTimelineData] = useState(
    Array.from({ length: 15 }, (_, i) => ({
      time: '-',
      transactions: 0,
      flagged: 0,
      blocked: 0
    }))
  );
  
  const [currentTelemetry, setCurrentTelemetry] = useState({
    transactions: 25000,
    flagged: 1300,
    blocked: 910
  });

  // Fetch initial data
  useEffect(() => {
    // Fetch Anomalies
    fetch(`${API_URL}/anomalies`)
      .then(res => res.json())
      .then(data => setNetworkAnomalies(data))
      .catch(err => console.error("Error fetching anomalies:", err));

    // Fetch Credit Profile (Mocking an ID)
    fetch(`${API_URL}/credit/CUST-88219`)
      .then(res => res.json())
      .then(data => setCreditProfile(data))
      .catch(err => console.error("Error fetching credit profile:", err));
  }, []);

  // Set up WebSocket
  useEffect(() => {
    const ws = new WebSocket(WS_URL);
    
    ws.onmessage = (event) => {
      const message = JSON.parse(event.data);
      if (message.type === 'telemetry_update') {
        const { time, transactions, flagged, blocked } = message.data;
        
        setCurrentTelemetry({ transactions, flagged, blocked });
        
        setFraudTimelineData(prev => {
          const newData = [...prev.slice(1), { time, transactions, flagged, blocked }];
          return newData;
        });
      }
    };

    return () => {
      ws.close();
    };
  }, []);

  const generateComplianceReport = () => {
    if (!creditProfile) return;
    
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text('FinGuard AI - Compliance Rationale Report', 14, 22);
    
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 30);
    doc.text(`Account ID: ${creditProfile.id}`, 14, 36);
    
    // Customer Info Section
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Customer Assessment Summary', 14, 48);
    
    // Autotable for profile info
    doc.autoTable({
      startY: 52,
      head: [['Attribute', 'Value']],
      body: [
        ['Customer Name', creditProfile.name],
        ['AI Credit Score', creditProfile.score.toString()],
        ['Model Recommendation', creditProfile.recommendation],
        ['Suggested Limit', `$${creditProfile.limit.toLocaleString()}`],
        ['Interest Tier', creditProfile.tier]
      ],
      theme: 'grid',
      headStyles: { fillColor: [0, 240, 255], textColor: 20 },
      styles: { fontSize: 11, cellPadding: 4 }
    });

    const finalY = doc.lastAutoTable.finalY + 14;

    // SHAP Explainability Section
    doc.setFontSize(14);
    doc.text('SHAP Behavior Factor Impact', 14, finalY);
    
    const factorsData = creditProfile.factors.map(f => [
      f.factor, 
      f.score.toString(), 
      f.avg.toString(),
      (f.score - f.avg) > 0 ? `+${(f.score - f.avg)}` : (f.score - f.avg).toString()
    ]);

    doc.autoTable({
      startY: finalY + 4,
      head: [['Behavioral Factor', 'Customer Score', 'Population Avg', 'Delta Impact']],
      body: factorsData,
      theme: 'striped',
      headStyles: { fillColor: [157, 78, 221] },
      styles: { fontSize: 10 }
    });

    // Final statement
    const textY = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    
    const rationaleText = doc.splitTextToSize(
      "Regulatory Rationale: The AI model utilizes alternative data factors per guidelines. " +
      "The SHAP explanation proves that strong on-time alternative utility payments offset " +
      "any thin traditional credit history attributes. No discriminatory variables (age, race, gender) " +
      "are utilized in compiling this credit evaluation.", 
      180
    );
    
    doc.text(rationaleText, 14, textY);

    // KYC Status Section
    const kycY = textY + 25;
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Latest KYC Verification Profile', 14, kycY);

    doc.autoTable({
      startY: kycY + 4,
      head: [['Identity Attribute', 'Verified Content']],
      body: [
        ['Customer Full Name', kycData.customerName || creditProfile.name],
        ['Linked Bank Account', kycData.accountNumber || 'ACC-9923-1120'],
        ['Aadhaar Number', kycData.aadhaarNumber || 'XXXX-XXXX-8921'],
        ['Mobile Number', kycData.mobileNumber || '+91 99XXXXXX01'],
        ['Biometric Liveness', capturedImage ? 'Verified (Local Match)' : 'Verified (Demo Registry)'],
        ['KYC Check Status', 'CLEARED - FIPS Level 3']
      ],
      theme: 'grid',
      headStyles: { fillColor: [52, 199, 89], textColor: 20 },
      styles: { fontSize: 10 }
    });

    if (capturedImage) {
      const finalImgY = doc.lastAutoTable.finalY + 10;
      doc.text('Biometric Match Snapshot', 14, finalImgY);
      doc.addImage(capturedImage, 'PNG', 14, finalImgY + 5, 40, 30);
    }

    // Save PDF
    doc.save(`Compliance_Report_${creditProfile.id}.pdf`);
  };

  const startCamera = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true });
      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }
      setCameraActive(true);
      setCapturedImage(null);
    } catch (err) {
      console.error("Error accessing camera:", err);
      addToast("Please allow camera permissions to proceed with Liveness Capture.", 'error');
    }
  };

  const captureImage = () => {
    if (videoRef.current && canvasRef.current) {
      const context = canvasRef.current.getContext('2d');
      // Set canvas size matching video resolving size
      canvasRef.current.width = videoRef.current.videoWidth;
      canvasRef.current.height = videoRef.current.videoHeight;
      context.drawImage(videoRef.current, 0, 0, canvasRef.current.width, canvasRef.current.height);
      const imgDataUrl = canvasRef.current.toDataURL('image/png');
      setCapturedImage(imgDataUrl);
      
      // Stop camera after capture if desired, or keep it running. Let's keep it running.
      addToast("Image Captured successfully! You can verify and submit.");
    }
  };

  // Clean up camera stream on unmount
  useEffect(() => {
    return () => {
      if (streamRef.current) {
        streamRef.current.getTracks().forEach(track => track.stop());
      }
    };
  }, []);

  const handleKYCSubmit = async () => {
    if (!capturedImage) {
      addToast("Please capture liveness photo first.", 'warning');
      return;
    }

    try {
      const payload = {
        ...kycData,
        image: capturedImage
      };

      const res = await fetch(`${API_URL}/kyc/submit`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      
      if (data.success) {
        addToast("KYC Processed Successfully! Report added to Compliance.", "success");
        generateKYCReport();
        
        // Log to compliance
        const reportId = `KYC-${Math.floor(1000 + Math.random() * 9000)}`;
        setComplianceLogs(prev => [{
          id: reportId,
          type: 'e-KYC Onboarding',
          entity: kycData.customerName || 'Unknown Customer',
          author: `admin@${selectedBank?.id || 'finguard'}.co.in`,
          time: 'Just Now',
          status: 'VERIFIED',
          statusColor: 'success'
        }, ...prev]);
        
        setTimeout(() => setActiveTab('compliance'), 1500);
      } else {
        addToast("Failed to process KYC.", 'error');
      }
    } catch (err) {
      console.error(err);
      
      // MOCK SUCCESS FOR OFFLINE DEMO
      const reportId = `KYC-${Math.floor(1000 + Math.random() * 9000)}`;
      setComplianceLogs(prev => [{
        id: reportId,
        type: 'e-KYC Onboarding',
        entity: kycData.customerName || 'Unknown Customer',
        author: `admin@${selectedBank?.id || 'finguard'}.co.in`,
        time: 'Just Now',
        status: 'VERIFIED',
        statusColor: 'success'
      }, ...prev]);
      
      addToast("KYC Processed Successfully! Report added.", 'success');
      setTimeout(() => setActiveTab('compliance'), 1500);
    }
  };

  const generateKYCReport = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text('e-KYC Submission Report', 14, 22);
    
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 30);
    
    // Customer Info Section
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Customer Details', 14, 48);
    
    doc.autoTable({
      startY: 52,
      head: [['Field', 'Details']],
      body: [
        ['Customer Name', kycData.customerName],
        ['Account Number', kycData.accountNumber],
        ['Bank Name', kycData.bankName],
        ['IFSC Code', kycData.ifscCode],
        ['Aadhaar Number', kycData.aadhaarNumber],
        ['Mobile Number', kycData.mobileNumber],
        ['Address', kycData.address],
      ],
      theme: 'grid',
      headStyles: { fillColor: [0, 240, 255], textColor: 20 },
      styles: { fontSize: 11, cellPadding: 4 }
    });

    const finalY = doc.lastAutoTable.finalY + 14;

    doc.setFontSize(14);
    doc.text('Liveness Capture', 14, finalY);
    if (capturedImage) {
      doc.addImage(capturedImage, 'PNG', 14, finalY + 5, 80, 60);
    }
    
    const safeName = kycData.customerName ? kycData.customerName.replace(/\s+/g, '_') : 'Customer';
    doc.save(`KYC_Report_${safeName}.pdf`);
  };

  const handleLogin = async (e) => {
    e.preventDefault();
    if (!selectedBank) return;
    
    // Assume form fields are ordered: 0 -> username, 1 -> password
    const username = e.target[0].value;
    const password = e.target[1].value;
    
    try {
      const res = await fetch(`${API_URL}/login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password })
      });
      const data = await res.json();
      
      if (data.success) {
        setCurrentUser(data.user);
        setIsAuthenticated(true);
        addToast(`Secure Connect: Verified ${data.user.branch_name} Branch node.`);
      } else {
        addToast("Invalid credentials, please try again.", 'error');
      }
    } catch (error) {
      console.error(error);
      addToast("Server connection error for login.", 'error');
      setIsAuthenticated(true); // Fallback
    }
  };

  const handleCaseAction = async (action, id) => {
    try {
      const res = await fetch(`${API_URL}/investigation/${action}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id })
      });
      const data = await res.json();
      if (data.success) {
        addToast(data.message);
        // Refresh anomalies if it's the fraud tab, but we're mocking it so just an alert is fine
      } else {
        addToast("Action failed.", 'error');
      }
    } catch (err) {
      console.error(err);
      addToast("Action locally recorded.", 'success');
    }
  };

  const supportedBanks = [
    { id: 'sbi', name: 'SBI', color: '#005596', logo: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/SBI-logo.svg' },
    { id: 'hdfc', name: 'HDFC Bank', color: '#004C8F', logo: 'https://1000logos.net/wp-content/uploads/2021/06/HDFC-Bank-logo.jpg' },
    { id: 'pnb', name: 'PNB', color: '#A32020', logo: 'https://static.vecteezy.com/system/resources/previews/020/336/282/original/punjab-national-bank-pnb-bank-logo-free-free-vector.jpg' },
    { id: 'bob', name: 'Bank of Baroda', color: '#F15A22', logo: 'https://1000logos.net/wp-content/uploads/2021/06/Bank-of-Baroda-logo.png' },
    { id: 'canara', name: 'Canara', color: '#005EB8', logo: 'https://www.liblogo.com/img-logo/ca8792c86d-canara-bank-logo-canara-bank-launches-qualified-institutional-placement.png' },
    { id: 'union', name: 'Union Bank', color: '#D52B1E', logo: 'https://www.bankingfinance.in/wp-content/uploads/2017/12/Union-Bank-of-India.jpg' },
    { id: 'boi', name: 'Bank of India', color: '#005A9C', logo: 'https://logos-world.net/wp-content/uploads/2020/01/Bank-of-India-Logo-before-2011.png' },
    { id: 'indian', name: 'Indian Bank', color: '#005EB8', logo: 'https://companieslogo.com/img/orig/INDIANB.NS_BIG-f675f730.png?t=1615846835' },
    { id: 'central', name: 'Central Bank', color: '#005EB8', logo: 'https://assets.stickpng.com/images/627cc6ac1b2e263b45696a95.png' },
    { id: 'iob', name: 'Indian Overseas', color: '#005A9C', logo: 'https://companieslogo.com/img/orig/IOB.NS_BIG-09a26177.png?t=1613454098' },
    { id: 'uco', name: 'UCO Bank', color: '#FFD700', logo: 'https://www.thebusinessquiz.com/wp-content/uploads/2014/11/UCO-Bank-Logo.jpg' },
    { id: 'bom', name: 'Maharashtra', color: '#005A9C', logo: 'https://assets.stickpng.com/images/627cc5c91b2e263b45696a8e.png' },
    { id: 'psb', name: 'Punjab & Sind', color: '#00703C', logo: 'https://assets.stickpng.com/images/627cce601b2e263b45696abb.png' }
  ];

  if (!isAuthenticated) {
    return (
      <>
        <ParticleBackground />
        <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'transparent' }}>
          <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
          className="glass-panel" 
          style={{ width: '100%', maxWidth: '520px', padding: '40px' }}
        >
          <div style={{ textAlign: 'center', marginBottom: '24px' }}>
            <ShieldAlert color="var(--accent-cyan)" size={48} style={{ margin: '0 auto 16px' }} />
            <h1 className="text-gradient" style={{ fontSize: '28px', marginBottom: '8px' }}>Central Fraud Intelligence</h1>
            <p style={{ color: 'var(--text-secondary)', fontSize: '14px' }}>Inter-Banking Security Authentication Portal</p>
          </div>
          
          {!selectedBank ? (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <p style={{ fontSize: '14px', marginBottom: '8px', textAlign: 'center' }}>Select your Financial Institution</p>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px', maxHeight: '400px', overflowY: 'auto', paddingRight: '4px' }}>
                {supportedBanks.map(bank => (
                  <button 
                    key={bank.id}
                    onClick={() => setSelectedBank(bank)}
                    style={{ 
                      padding: '12px 8px', 
                      background: 'rgba(255,255,255,0.03)', 
                      border: '1px solid rgba(255,255,255,0.1)', 
                      borderRadius: '8px',
                      display: 'flex',
                      flexDirection: 'column',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '8px',
                      cursor: 'pointer',
                      transition: 'all 0.2s ease',
                    }}
                    onMouseOver={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.08)'; e.currentTarget.style.borderColor = bank.color }}
                    onMouseOut={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; e.currentTarget.style.borderColor = 'rgba(255,255,255,0.1)' }}
                  >
                    <div style={{ width: '76px', height: '76px', background: '#fff', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', border: `2px solid rgba(255,255,255,0.1)` }}>
                      <img 
                        src={bank.logo} 
                        alt={bank.name} 
                        style={{ width: '100%', height: '100%', objectFit: 'contain', padding: '6px' }} 
                        onError={(e) => { e.target.style.display = 'none'; e.target.nextSibling.style.display = 'flex'; }}
                      />
                      <span style={{ display: 'none', color: '#333', fontWeight: 'bold', fontSize: '20px', alignItems: 'center', justifyContent: 'center', width: '100%', height: '100%' }}>{bank.name.substring(0,2)}</span>
                    </div>
                    <span style={{ fontWeight: 500, fontSize: '11px', textAlign: 'center', color: 'white' }}>{bank.name}</span>
                  </button>
                ))}
              </div>
            </motion.div>
          ) : (
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}>
              <div style={{ padding: '12px', background: 'rgba(255,255,255,0.05)', borderRadius: '8px', marginBottom: '20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <span style={{ fontSize: '16px', fontWeight: '500', color: selectedBank.color, display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <div style={{ background: '#fff', borderRadius: '6px', padding: '4px', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', height: '36px', width: '36px' }}>
                    <img src={selectedBank.logo} alt="" style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' }} onError={(e) => e.target.style.display = 'none'} />
                  </div>
                  {selectedBank.name} Portal
                </span>
                <span style={{ fontSize: '12px', color: 'var(--text-secondary)', cursor: 'pointer', textDecoration: 'underline' }} onClick={() => setSelectedBank(null)}>Change Bank</span>
              </div>
              <form onSubmit={handleLogin} style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                <div>
                  <label style={{ display: 'block', marginBottom: '6px', fontSize: '13px', color: 'var(--text-secondary)' }}>Bank Official Username</label>
                  <input type="text" placeholder={`e.g. employee@${selectedBank.id}.co.in`} defaultValue={`admin@${selectedBank.id}.co.in`} style={{ width: '100%', padding: '12px', borderRadius: '8px', background: 'rgba(255,255,255,0.05)', border: '1px solid var(--panel-border)', color: 'white', outline: 'none' }} required />
                </div>
                <div>
                  <label style={{ display: 'block', marginBottom: '6px', fontSize: '13px', color: 'var(--text-secondary)' }}>Security Phase Key</label>
                  <input type="password" placeholder="••••••••" defaultValue="password" style={{ width: '100%', padding: '12px', borderRadius: '8px', background: 'rgba(255,255,255,0.05)', border: '1px solid var(--panel-border)', color: 'white', outline: 'none' }} required />
                </div>
                
                <button type="submit" className="btn btn-primary" style={{ width: '100%', justifyContent: 'center', marginTop: '16px', padding: '14px' }}>
                  Secure Login to Network
                </button>
              </form>
            </motion.div>
          )}
          
          <div style={{ marginTop: '24px', textAlign: 'center', fontSize: '12px', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px' }}>
            <FileKey size={14} /> FIPS 140-2 Compliant Node
          </div>
        </motion.div>
      </div>
      </>
    );
  }

  return (
    <>
      <ParticleBackground />
      <div className="app-container">
        {/* Sidebar */}
      <div className="sidebar">
        <div className="logo" style={{ flexDirection: 'column', alignItems: 'flex-start', gap: '4px', marginBottom: '30px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <ShieldAlert color="var(--accent-cyan)" size={24} />
            <span className="text-gradient">CFI Network</span>
          </div>
          <div style={{ fontSize: '12px', color: 'var(--text-secondary)', paddingLeft: '36px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              Connected to 
              <div style={{ background: '#fff', borderRadius: '6px', padding: '4px', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', height: '40px', width: '40px' }}>
                <img src={selectedBank.logo} alt="" style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' }} onError={(e) => e.target.style.display = 'none'} />
              </div>
              <strong style={{ fontSize: '16px', color: 'white' }}>{selectedBank.name}</strong>
            </div>
            {currentUser && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', background: 'rgba(255,255,255,0.03)', padding: '10px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.05)', marginTop: '4px', width: '100%', maxWidth: '180px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span style={{ fontSize: '14px' }}>🏦</span> <span style={{ color: 'white', fontWeight: 500 }}>{currentUser.branch_name} Branch</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span style={{ fontSize: '14px' }}>📍</span> <span>{currentUser.city}</span>
                </div>
                <div style={{ marginTop: '6px', paddingTop: '6px', borderTop: '1px solid rgba(255,255,255,0.05)', display: 'flex', alignItems: 'center', gap: '4px', color: 'var(--success)', fontSize: '10px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                  <CheckCircle size={12} /> Secure Node Verified
                </div>
              </div>
            )}
          </div>
        </div>
        
        <div className="nav-menu">
          <div className={`nav-item ${activeTab === 'fraud' ? 'active' : ''}`} onClick={() => setActiveTab('fraud')}>
            <Network size={20} />
            Graph Fraud Detection
          </div>
          <div className={`nav-item ${activeTab === 'credit' ? 'active' : ''}`} onClick={() => setActiveTab('credit')}>
            <BarChart3 size={20} />
            Credit Risk Modeling
          </div>
          <div className={`nav-item ${activeTab === 'investigation' ? 'active' : ''}`} onClick={() => setActiveTab('investigation')}>
            <Users size={20} />
            Entity Investigation
          </div>
          <div className={`nav-item ${activeTab === 'freeze_tracker' ? 'active' : ''}`} onClick={() => setActiveTab('freeze_tracker')}>
            <Lock size={20} />
            Freeze Source Tracker
          </div>
          <div className={`nav-item ${activeTab === 'kyc' ? 'active' : ''}`} onClick={() => setActiveTab('kyc')}>
            <ScanFace size={20} />
            e-KYC Processing
          </div>
          <div className={`nav-item ${activeTab === 'compliance' ? 'active' : ''}`} onClick={() => setActiveTab('compliance')}>
            <FileKey size={20} />
            Compliance Reports
          </div>
          <div className={`nav-item ${activeTab === 'file_complaint' ? 'active' : ''}`} onClick={() => setActiveTab('file_complaint')}>
            <AlertOctagon size={20} />
            File a Complaint
          </div>
        </div>

        <div style={{ marginTop: 'auto', padding: '20px 0', borderTop: '1px solid var(--panel-border)' }}>
          <div className="live-indicator mb-4">
            <div className="pulse"></div>
            System Online & Active
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="main-content">
        <div className="header">
          <div className="header-title">
            <h1 className="text-gradient">
              {activeTab === 'fraud' ? 'Real-Time Network Intelligence' : 'Explainable AI Assessment'}
            </h1>
            <p>
              {activeTab === 'fraud' 
                ? 'Graph-based anomaly detection across multi-layer transaction networks. Live Telemetry enabled.'
                : 'Interpretable risk scoring framework combining behavioral and financial features.'}
            </p>
          </div>
          
          <div style={{ display: 'flex', gap: '16px', alignItems: 'center' }}>
            <div className="glass-panel" style={{ padding: '8px 16px', borderRadius: '20px', display: 'flex', gap: '8px', alignItems: 'center' }}>
              <Search size={16} color="var(--text-secondary)" />
              <input type="text" placeholder="Search entity or TXN..." style={{ background: 'transparent', border: 'none', color: 'white', outline: 'none' }} />
            </div>
            <button className="btn" style={{ background: 'transparent', padding: '8px' }}>
              <Bell size={20} />
            </button>
            <div style={{ width: '40px', height: '40px', borderRadius: '50%', background: 'linear-gradient(135deg, var(--accent-purple), var(--accent-cyan))', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' }}>
              AD
            </div>
          </div>
        </div>

        <AnimatePresence mode="wait">
          {activeTab === 'fraud' ? (
            <motion.div 
              key="fraud"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
              className="dashboard-grid"
            >
              {/* Stats */}
              <div className="glass-panel stat-card">
                <div className="stat-card-title">Live Transactions</div>
                <div className="stat-card-value">
                  {currentTelemetry.transactions.toLocaleString()}
                  <Activity size={20} color="var(--accent-cyan)" />
                </div>
                <div className="stat-card-change change-positive">Streaming</div>
              </div>
              <div className="glass-panel stat-card" data-suspicious="true">
                <div className="stat-card-title">Ongoing Anomalies (Flagged)</div>
                <div className="stat-card-value">
                  {currentTelemetry.flagged.toLocaleString()}
                  <AlertTriangle size={20} color="var(--warning)" />
                </div>
                <div className="stat-card-change change-warning">Review Required</div>
              </div>
              <div className="glass-panel stat-card">
                <div className="stat-card-title">Instantly Blocked</div>
                <div className="stat-card-value">
                  {currentTelemetry.blocked.toLocaleString()}
                  <ShieldAlert size={20} color="var(--success)" />
                </div>
                <div className="stat-card-change change-positive">Auto-Interception active</div>
              </div>
              <div className="glass-panel stat-card">
                <div className="stat-card-title">False Positive Rate</div>
                <div className="stat-card-value text-gradient">
                  0.12%
                </div>
                <div className="stat-card-change change-positive">-0.05% optimization</div>
              </div>

              {/* Main Graph */}
              <div className="glass-panel graph-panel">
                <div className="panel-header">
                  <div className="panel-title">
                    <Activity size={18} color="var(--accent-cyan)" />
                    Transaction Volume vs Anomalies (Live Flow)
                  </div>
                </div>
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={fraudTimelineData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
                    <defs>
                      <linearGradient id="colorTxns" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="var(--accent-cyan)" stopOpacity={0.3}/>
                        <stop offset="95%" stopColor="var(--accent-cyan)" stopOpacity={0}/>
                      </linearGradient>
                      <linearGradient id="colorFlagged" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="var(--danger)" stopOpacity={0.5}/>
                        <stop offset="95%" stopColor="var(--danger)" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--panel-border)" vertical={false} />
                    <XAxis dataKey="time" stroke="var(--text-secondary)" fontSize={12} tickLine={false} axisLine={false} />
                    <YAxis stroke="var(--text-secondary)" fontSize={12} tickLine={false} axisLine={false} />
                    <Tooltip 
                      contentStyle={{ background: 'var(--panel-bg)', borderColor: 'var(--panel-border)', borderRadius: '8px', color: '#fff' }}
                      itemStyle={{ color: '#fff' }}
                    />
                    <Area type="monotone" dataKey="transactions" stroke="var(--accent-cyan)" fillOpacity={1} fill="url(#colorTxns)" isAnimationActive={false} />
                    <Area type="monotone" dataKey="flagged" stroke="var(--danger)" fillOpacity={1} fill="url(#colorFlagged)" isAnimationActive={false} />
                  </AreaChart>
                </ResponsiveContainer>
              </div>

              {/* Alerts List */}
              <div className="glass-panel side-panel" data-suspicious="true">
                <div className="panel-header">
                  <div className="panel-title">
                    <AlertTriangle size={18} color="var(--warning)" />
                    High-Risk Entities (DB Synced)
                  </div>
                  <button className="btn" style={{ fontSize: '12px' }}>View All <ArrowUpRight size={14}/></button>
                </div>
                <div className="entity-list">
                  {networkAnomalies.length > 0 ? networkAnomalies.map((entity, i) => (
                    <div key={i} className="entity-item">
                      <div className="entity-info">
                        <span className="entity-name">{entity.entity}</span>
                        <span className="entity-id">{entity.id} • {entity.type}</span>
                      </div>
                      <div className="entity-score">
                        <span className={`badge ${entity.risk > 90 ? 'badge-high' : entity.risk > 80 ? 'badge-medium' : 'badge-low'}`}>
                          Risk {entity.risk}
                        </span>
                      </div>
                    </div>
                  )) : (
                    <div style={{color: 'var(--text-secondary)', padding: '20px', textAlign: 'center'}}>Loading data...</div>
                  )}
                </div>
              </div>
            </motion.div>
          ) : activeTab === 'credit' ? (
            <motion.div 
              key="credit"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
              className="dashboard-grid"
            >
              {creditProfile ? (
              <>
                {/* Profile Card */}
                <div className="glass-panel" style={{ gridColumn: 'span 4' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '24px' }}>
                    <div style={{ width: '64px', height: '64px', borderRadius: '50%', background: 'linear-gradient(135deg, var(--accent-purple), var(--accent-cyan))', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '24px', fontWeight: 'bold' }}>
                      {creditProfile.name.split(' ').map(n=>n[0]).join('')}
                    </div>
                    <div>
                      <h2 style={{ fontSize: '20px', fontWeight: '600' }}>{creditProfile.name}</h2>
                      <p style={{ color: 'var(--text-secondary)', fontSize: '14px' }}>ID: {creditProfile.id}</p>
                    </div>
                  </div>

                  <div style={{ padding: '20px', background: 'rgba(0,240,255,0.05)', borderRadius: '12px', border: '1px solid rgba(0,240,255,0.1)', textAlign: 'center', marginBottom: '24px' }}>
                    <div style={{ fontSize: '14px', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '8px' }}>AI Credit Score</div>
                    <div className="text-gradient" style={{ fontSize: '48px', fontWeight: '800', lineHeight: '1' }}>{creditProfile.score}</div>
                    <div style={{ marginTop: '8px', color: 'var(--success)', fontSize: '14px', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px' }}>
                      <TrendingUp size={14} /> Model Validated
                    </div>
                  </div>

                  <div className="panel-title mb-4">Risk Factors Attribution</div>
                  <div className="risk-factors">
                    <div className="risk-factor">
                      <div className="risk-factor-header">
                        <span>Payment Consistency</span>
                        <span className="text-gradient">High Positive Impact (+45)</span>
                      </div>
                      <div className="progress-bar-bg"><div className="progress-bar-fill" style={{ width: '85%', background: 'var(--success)' }}></div></div>
                    </div>
                    <div className="risk-factor">
                      <div className="risk-factor-header">
                        <span>Credit Utilization (32%)</span>
                        <span style={{ color: 'var(--warning)' }}>Moderate Impact (-10)</span>
                      </div>
                      <div className="progress-bar-bg"><div className="progress-bar-fill" style={{ width: '68%', background: 'var(--warning)' }}></div></div>
                    </div>
                    <div className="risk-factor">
                      <div className="risk-factor-header">
                        <span>Alternative Data (Utility Bills)</span>
                        <span className="text-gradient">Positive Impact (+15)</span>
                      </div>
                      <div className="progress-bar-bg"><div className="progress-bar-fill" style={{ width: '75%', background: 'var(--accent-cyan)' }}></div></div>
                    </div>
                  </div>
                </div>

                {/* Radar Chart */}
                <div className="glass-panel" style={{ gridColumn: 'span 4', display: 'flex', flexDirection: 'column' }}>
                  <div className="panel-header">
                    <div className="panel-title">Behavioral Modeling Profile</div>
                  </div>
                  <div style={{ flex: 1, minHeight: '300px' }}>
                    <ResponsiveContainer width="100%" height="100%">
                      <RadarChart cx="50%" cy="50%" outerRadius="70%" data={creditProfile.factors}>
                        <PolarGrid stroke="var(--panel-border)" />
                        <PolarAngleAxis dataKey="factor" tick={{ fill: 'var(--text-secondary)', fontSize: 11 }} />
                        <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                        <Radar name={creditProfile.name} dataKey="score" stroke="var(--accent-cyan)" fill="var(--accent-cyan)" fillOpacity={0.5} />
                        <Radar name="Population Avg" dataKey="avg" stroke="var(--text-secondary)" fill="var(--text-secondary)" fillOpacity={0.2} strokeDasharray="3 3" />
                        <Tooltip 
                          contentStyle={{ background: 'var(--panel-bg)', borderColor: 'var(--panel-border)', borderRadius: '8px' }}
                        />
                      </RadarChart>
                    </ResponsiveContainer>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'center', gap: '16px', fontSize: '13px', color: 'var(--text-secondary)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                      <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: 'var(--accent-cyan)' }}></div> Customer Profile
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                      <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: 'var(--text-secondary)', opacity: 0.5 }}></div> Population Average
                    </div>
                  </div>
                </div>

                {/* Approvals */}
                <div className="glass-panel" style={{ gridColumn: 'span 4' }}>
                  <div className="panel-header">
                    <div className="panel-title">Model Explainability Output</div>
                  </div>
                  <p style={{ color: 'var(--text-secondary)', fontSize: '14px', lineHeight: '1.6', marginBottom: '24px' }}>
                    The SHAP (SHapley Additive exPlanations) values indicate that the customer's on-time utility payments (alternative data) significantly offset their thin traditional credit file, pushing the decision boundary beyond the threshold for approval.
                  </p>

                  <div style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid var(--panel-border)', borderRadius: '8px', padding: '16px', marginBottom: '16px' }}>
                    <div style={{ fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '8px' }}>RECOMMENDATION</div>
                    <div style={{ color: 'var(--success)', fontSize: '18px', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '8px' }}>
                      {creditProfile.recommendation} <ShieldAlert size={18} />
                    </div>
                    <div style={{ borderTop: '1px dashed rgba(255,255,255,0.1)', margin: '12px 0' }}></div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '13px' }}>
                      <span style={{ color: 'var(--text-secondary)' }}>Suggested Limit:</span>
                      <span style={{ color: 'white', fontWeight: '500' }}>${creditProfile.limit.toLocaleString()}</span>
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '13px', marginTop: '8px' }}>
                      <span style={{ color: 'var(--text-secondary)' }}>Interest Tier:</span>
                      <span style={{ color: 'white', fontWeight: '500' }}>{creditProfile.tier}</span>
                    </div>
                  </div>

                  <button 
                    className="btn btn-primary" 
                    style={{ width: '100%', justifyContent: 'center' }}
                    onClick={generateComplianceReport}
                  >
                    Generate Compliance Rationale Report
                  </button>
                </div>
              </>
              ) : (
                <div style={{gridColumn: 'span 12', color: 'white', textAlign: 'center', padding: '40px'}}>Loading Credit Risk Profile from Backend...</div>
              )}
            </motion.div>
          ) : activeTab === 'investigation' ? (
            <motion.div 
              key="investigation"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
              style={{ padding: '0' }}
            >
              <EntityInvestigation 
                addToast={addToast} 
                setComplianceLogs={setComplianceLogs} 
                selectedBank={selectedBank} 
              />
            </motion.div>
          ) : activeTab === 'freeze_tracker' ? (
            <motion.div 
              key="freeze_tracker"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
              className="dashboard-grid"
            >
              <div className="glass-panel" style={{ gridColumn: 'span 12' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
                  <div>
                    <h2 style={{ fontSize: '20px', fontWeight: '600' }}>Freeze Source Tracker</h2>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '14px' }}>Trace account freeze & block origins across inter-bank branches.</p>
                  </div>
                  <div style={{ fontSize: '12px', background: 'rgba(255,255,255,0.05)', padding: '6px 12px', borderRadius: '20px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <Lock size={14} color="var(--accent-cyan)" />
                    Accessing from: {currentUser?.branch_name}, {currentUser?.city}
                  </div>
                </div>

                <form onSubmit={handleFreezeSearch} style={{ display: 'flex', gap: '16px', marginBottom: '30px' }}>
                  <input 
                    type="text" 
                    placeholder="Enter Customer ID, Account No, or Name (e.g. CUST001)" 
                    value={freezeSearchInput}
                    onChange={(e) => setFreezeSearchInput(e.target.value)}
                    autoFocus
                    style={{ flex: 1, padding: '14px', borderRadius: '8px', background: 'rgba(255,255,255,0.02)', border: '1px solid var(--panel-border)', color: 'white', outline: 'none' }}
                  />
                  <button type="submit" className="btn btn-primary" style={{ padding: '0 24px', display: 'flex', gap: '8px', alignItems: 'center' }} disabled={isFreezeSearching}>
                    {isFreezeSearching ? <div className="pulse" style={{width: 16, height: 16}}></div> : <Search size={18} />}
                    Search Trace
                  </button>
                </form>

                {isFreezeSearching && (
                  <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text-secondary)' }}>
                    <div className="pulse" style={{ width: 30, height: 30, margin: '0 auto 16px', background: 'var(--accent-cyan)' }}></div>
                     Querying FI Network Nodes...
                  </div>
                )}

                {!isFreezeSearching && hasSearched && !freezeSearchResults && (
                  <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text-secondary)' }}>
                     <AlertTriangle size={32} style={{ margin: '0 auto 12px', opacity: 0.5 }} />
                     No freeze or block trace found for this input.
                  </div>
                )}

                {!isFreezeSearching && freezeSearchResults && (
                  <div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px', padding: '16px', background: 'rgba(0,0,0,0.2)', borderRadius: '8px', borderLeft: `4px solid ${freezeSearchResults.status === 'Blocked' ? 'var(--danger)' : freezeSearchResults.status === 'Frozen' ? 'var(--warning)' : 'var(--success)'}` }}>
                      <div>
                         <div style={{ fontSize: '18px', fontWeight: 'bold' }}>{freezeSearchResults.name}</div>
                         <div style={{ color: 'var(--text-secondary)', fontSize: '13px' }}>ID: {freezeSearchResults.customerId} | Acc: {freezeSearchResults.accountNumber}</div>
                      </div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                        <div style={{ padding: '6px 12px', borderRadius: '4px', background: freezeSearchResults.status === 'Blocked' ? 'rgba(255,70,70,0.1)' : 'rgba(255,180,0,0.1)', color: freezeSearchResults.status === 'Blocked' ? 'var(--danger)' : 'var(--warning)', fontWeight: 'bold', fontSize: '14px' }}>
                           STATUS: {freezeSearchResults.status.toUpperCase()}
                        </div>
                        <button className="btn" onClick={() => setActiveTab('investigation')} style={{ display: 'flex', gap: '6px', alignItems: 'center', fontSize: '13px' }}>
                           <Network size={14} /> View in Graph
                        </button>
                      </div>
                    </div>
                    
                    <h3 style={{ fontSize: '16px', marginBottom: '16px', color: 'var(--text-secondary)' }}>Action Trace Timeline</h3>
                    <div style={{ position: 'relative', paddingLeft: '24px' }}>
                      <div style={{ position: 'absolute', top: '10px', bottom: '10px', left: '7px', width: '2px', background: 'var(--panel-border)' }}></div>
                      {freezeSearchResults.actions.map((act, i) => (
                         <div key={i} style={{ position: 'relative', marginBottom: i === freezeSearchResults.actions.length - 1 ? 0 : '24px', background: 'rgba(255,255,255,0.02)', padding: '16px', borderRadius: '8px', border: '1px solid var(--panel-border)' }}>
                           <div style={{ position: 'absolute', left: '-22px', top: '24px', width: '10px', height: '10px', borderRadius: '50%', background: act.action.includes('Block') ? 'var(--danger)' : act.action.includes('Freeze') ? 'var(--warning)' : act.action.includes('Suspicious') ? 'var(--accent-purple)' : 'var(--success)', border: '2px solid var(--panel-bg)', zIndex: 1 }}></div>
                           <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                             <div style={{ fontWeight: 'bold', fontSize: '15px', color: act.action.includes('Block') ? 'var(--danger)' : act.action.includes('Freeze') ? 'var(--warning)' : 'white' }}>{act.action}</div>
                             <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>{act.timestamp}</div>
                           </div>
                           <div style={{ display: 'flex', gap: '16px', fontSize: '13px', color: 'var(--text-secondary)', marginBottom: '8px' }}>
                             <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>🏦 {act.bank} - {act.branch}</span>
                             <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>📍 {act.city}</span>
                           </div>
                           <div style={{ fontSize: '13px', padding: '8px', background: 'rgba(0,0,0,0.3)', borderRadius: '4px', borderLeft: '2px solid var(--accent-cyan)' }}>
                             <strong>Reason:</strong> {act.reason}
                           </div>
                         </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </motion.div>
          ) : activeTab === 'kyc' ? (
            <motion.div 
              key="kyc"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
              className="dashboard-grid"
            >
              <div className="glass-panel" style={{ gridColumn: 'span 12', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                  <h2 style={{ fontSize: '20px', fontWeight: '600' }}>UIDAI e-KYC Verification & Onboarding</h2>
                  <p style={{ color: 'var(--text-secondary)', fontSize: '14px' }}>Aadhaar OTP + Liveness Real-time Image Capture Verification</p>
                </div>
                <div style={{ padding: '6px 12px', background: 'rgba(52, 199, 89, 0.1)', color: 'var(--success)', borderRadius: '20px', border: '1px solid rgba(52, 199, 89, 0.3)', fontSize: '12px', fontWeight: 'bold' }}>UIDAI GATEWAY: ONLINE</div>
              </div>

              <div className="glass-panel" style={{ gridColumn: 'span 7', minHeight: '400px' }}>
                <div className="panel-header">
                  <div className="panel-title"><Users size={18} color="var(--accent-cyan)" /> Customer Identification Data</div>
                </div>
                
                <form style={{ display: 'flex', flexDirection: 'column', gap: '20px', marginTop: '12px' }}>
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                    <div>
                      <label style={{ display: 'block', marginBottom: '8px', fontSize: '13px', color: 'var(--text-secondary)' }}>Customer Full Name</label>
                      <input type="text" value={kycData.customerName} onChange={(e) => setKycData({...kycData, customerName: e.target.value})} placeholder="As per bank records" style={{ width: '100%', padding: '12px', borderRadius: '8px', background: 'rgba(255,255,255,0.03)', border: '1px solid var(--panel-border)', color: 'white', outline: 'none' }} />
                    </div>
                    <div>
                      <label style={{ display: 'block', marginBottom: '8px', fontSize: '13px', color: 'var(--text-secondary)' }}>Account Number</label>
                      <input type="text" value={kycData.accountNumber} onChange={(e) => setKycData({...kycData, accountNumber: e.target.value})} placeholder="Account Number" style={{ width: '100%', padding: '12px', borderRadius: '8px', background: 'rgba(255,255,255,0.03)', border: '1px solid var(--panel-border)', color: 'white', outline: 'none' }} />
                    </div>
                    <div>
                      <label style={{ display: 'block', marginBottom: '8px', fontSize: '13px', color: 'var(--text-secondary)' }}>Bank Name</label>
                      <input type="text" value={kycData.bankName} onChange={(e) => setKycData({...kycData, bankName: e.target.value})} placeholder="e.g. SBI, HDFC" style={{ width: '100%', padding: '12px', borderRadius: '8px', background: 'rgba(255,255,255,0.03)', border: '1px solid var(--panel-border)', color: 'white', outline: 'none' }} />
                    </div>
                    <div>
                      <label style={{ display: 'block', marginBottom: '8px', fontSize: '13px', color: 'var(--text-secondary)' }}>IFSC Code</label>
                      <input type="text" value={kycData.ifscCode} onChange={(e) => setKycData({...kycData, ifscCode: e.target.value})} placeholder="IFSC Code" style={{ width: '100%', padding: '12px', borderRadius: '8px', background: 'rgba(255,255,255,0.03)', border: '1px solid var(--panel-border)', color: 'white', outline: 'none' }} />
                    </div>
                    <div>
                      <label style={{ display: 'block', marginBottom: '8px', fontSize: '13px', color: 'var(--text-secondary)' }}>Aadhaar Number</label>
                      <input type="text" value={kycData.aadhaarNumber} onChange={(e) => setKycData({...kycData, aadhaarNumber: e.target.value})} placeholder="XXXX - XXXX - XXXX" style={{ width: '100%', padding: '12px', borderRadius: '8px', background: 'rgba(255,255,255,0.03)', border: '1px solid var(--panel-border)', color: 'white', outline: 'none', letterSpacing: '2px' }} />
                    </div>
                    <div>
                      <label style={{ display: 'block', marginBottom: '8px', fontSize: '13px', color: 'var(--text-secondary)' }}>Linked Mobile Number</label>
                      <input type="text" value={kycData.mobileNumber} onChange={(e) => setKycData({...kycData, mobileNumber: e.target.value})} placeholder="+91 9XXXX XXXX" style={{ width: '100%', padding: '12px', borderRadius: '8px', background: 'rgba(255,255,255,0.03)', border: '1px solid var(--panel-border)', color: 'white', outline: 'none' }} />
                    </div>
                  </div>
                  
                  <div style={{ display: 'flex', gap: '12px', marginTop: '8px' }}>
                     <button type="button" className="btn btn-primary" style={{ flex: 1, justifyContent: 'center' }}>Request Aadhaar OTP</button>
                     <input type="text" placeholder="Enter 6-digit OTP" style={{ flex: 1, padding: '12px', borderRadius: '8px', background: 'rgba(0,0,0,0.2)', border: '1px dotted var(--accent-cyan)', color: 'var(--accent-cyan)', outline: 'none', textAlign: 'center', letterSpacing: '4px' }} />
                  </div>

                  <div style={{ borderTop: '1px solid var(--panel-border)', margin: '16px 0' }}></div>

                  <div>
                     <label style={{ display: 'block', marginBottom: '8px', fontSize: '13px', color: 'var(--text-secondary)' }}>Residential Address</label>
                     <textarea placeholder="Enter address..." value={kycData.address} onChange={(e) => setKycData({...kycData, address: e.target.value})} style={{ width: '100%', padding: '12px', borderRadius: '8px', background: 'rgba(255,255,255,0.02)', border: '1px solid var(--panel-border)', color: 'white', outline: 'none', resize: 'none', minHeight: '80px' }}></textarea>
                  </div>
                </form>
              </div>

              <div className="glass-panel" style={{ gridColumn: 'span 5', display: 'flex', flexDirection: 'column', gap: '16px' }}>
                <div className="panel-header">
                  <div className="panel-title"><ScanFace size={18} color="var(--accent-purple)" /> Liveness Image Capture</div>
                </div>
                
                <div style={{ flex: 1, background: 'rgba(0,0,0,0.4)', borderRadius: '12px', border: '1px dashed var(--panel-border)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '20px', position: 'relative', overflow: 'hidden' }}>
                    {capturedImage ? (
                      <img src={capturedImage} alt="Captured Liveness" style={{ width: '100%', height: '100%', objectFit: 'cover', borderRadius: '8px' }} />
                    ) : (
                      <>
                        <video 
                          ref={videoRef} 
                          autoPlay 
                          playsInline 
                          muted 
                          style={{ width: '100%', height: '100%', objectFit: 'cover', borderRadius: '8px', display: cameraActive ? 'block' : 'none' }}
                        ></video>
                        
                        {!cameraActive && (
                          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                            <ScanFace size={64} color="var(--text-secondary)" style={{ opacity: 0.5, marginBottom: '16px' }} />
                            <p style={{ color: 'var(--text-secondary)', fontSize: '13px', textAlign: 'center' }}>Awaiting Camera Permissions...</p>
                          </div>
                        )}
                        
                        {/* Camera UI Guidelines overlay */}
                        <div style={{ position: 'absolute', width: '180px', height: '240px', border: '2px dashed rgba(0, 240, 255, 0.5)', borderRadius: '120px', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', pointerEvents: 'none', display: cameraActive ? 'block' : 'none' }}></div>
                      </>
                    )}
                    <canvas ref={canvasRef} style={{ display: 'none' }}></canvas>
                </div>

                <div style={{ display: 'flex', gap: '12px' }}>
                  {!cameraActive ? (
                    <button type="button" onClick={startCamera} className="btn" style={{ flex: 1, background: 'rgba(255,255,255,0.05)', textAlign: 'center', justifyContent: 'center' }}>Enable Camera</button>
                  ) : (
                    <button type="button" onClick={captureImage} className="btn" style={{ flex: 1, background: 'rgba(0, 240, 255, 0.1)', color: 'var(--accent-cyan)', border: '1px solid rgba(0, 240, 255, 0.3)', textAlign: 'center', justifyContent: 'center' }}>Capture Photo</button>
                  )}
                  <button type="button" onClick={handleKYCSubmit} className="btn btn-primary" style={{ flex: 1, justifyContent: 'center', background: 'var(--success)', borderColor: 'var(--success)' }}>Verify Liveness & Submit</button>
                </div>
              </div>
            </motion.div>
          ) : activeTab === 'compliance' ? (
            <motion.div 
              key="compliance"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
              className="dashboard-grid"
            >
              <div className="glass-panel" style={{ gridColumn: 'span 12', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                  <h2 style={{ fontSize: '20px', fontWeight: '600' }}>Regulatory Filing & Compliance Vault</h2>
                  <p style={{ color: 'var(--text-secondary)', fontSize: '14px' }}>FIPS 140-2 Audited Logs • Retained for 7 Years</p>
                </div>
                <button className="btn btn-primary"><Search size={16} style={{marginRight: '6px'}}/> Query Archives</button>
              </div>

              <div className="glass-panel" style={{ gridColumn: 'span 8', minHeight: '400px' }}>
                <div className="panel-header">
                  <div className="panel-title"><FileKey size={18} color="var(--accent-purple)" /> Document Master Log</div>
                  <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
                    {selectedLogs.length > 0 && (
                      <button onClick={handleDeleteSelectedLogs} className="btn" style={{ background: 'rgba(255, 59, 48, 0.1)', color: 'var(--danger)', border: '1px solid rgba(255, 59, 48, 0.3)', padding: '6px 12px', fontSize: '12px' }}>
                        Delete Selected ({selectedLogs.length})
                      </button>
                    )}
                    <button onClick={handleExportCSV} className="btn btn-primary" style={{ padding: '6px 12px', fontSize: '12px' }}>
                      Export to CSV 
                    </button>
                  </div>
                </div>
                <table style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse', fontSize: '13px' }}>
                  <thead>
                    <tr style={{ borderBottom: '1px solid var(--panel-border)', color: 'var(--text-secondary)' }}>
                      <th style={{ padding: '12px 8px', width: '30px' }}>
                        <input 
                          type="checkbox" 
                          checked={complianceLogs.length > 0 && selectedLogs.length === complianceLogs.length}
                          onChange={handleSelectAllLogs}
                          style={{ accentColor: 'var(--accent-cyan)', cursor: 'pointer' }}
                        />
                      </th>
                      <th style={{ padding: '12px 8px' }}>Report ID</th>
                      <th style={{ padding: '12px 8px' }}>Type</th>
                      <th style={{ padding: '12px 8px' }}>Target Entity</th>
                      <th style={{ padding: '12px 8px' }}>Generated By</th>
                      <th style={{ padding: '12px 8px' }}>Timestamp</th>
                      <th style={{ padding: '12px 8px' }}>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <AnimatePresence>
                      {complianceLogs.map((log) => (
                        <motion.tr 
                          key={log.id}
                          initial={{ opacity: 0, y: -20, backgroundColor: 'rgba(0, 240, 255, 0.2)' }}
                          animate={{ opacity: 1, y: 0, backgroundColor: 'transparent' }}
                          transition={{ duration: 0.5 }}
                          style={{ borderBottom: '1px solid rgba(255,255,255,0.02)' }}
                        >
                          <td style={{ padding: '12px 8px' }}>
                            <input 
                              type="checkbox" 
                              checked={selectedLogs.includes(log.id)}
                              onChange={() => handleSelectLog(log.id)}
                              style={{ accentColor: 'var(--accent-cyan)', cursor: 'pointer' }}
                            />
                          </td>
                          <td style={{ padding: '12px 8px', color: 'var(--accent-cyan)' }}>{log.id}</td>
                          <td style={{ padding: '12px 8px' }}>{log.type}</td>
                          <td style={{ padding: '12px 8px', fontWeight: log.type === 'e-KYC Onboarding' ? '600' : 'normal' }}>{log.entity}</td>
                          <td style={{ padding: '12px 8px' }}>{log.author}</td>
                          <td style={{ padding: '12px 8px' }}>{log.time}</td>
                          <td style={{ padding: '12px 8px' }}>
                            <span className={`badge ${
                              log.statusColor === 'high' ? 'badge-high' : 
                              log.statusColor === 'medium' ? 'badge-medium' : 
                              log.statusColor === 'success' ? 'badge-success' : 'badge-low'
                            }`}>{log.status}</span>
                          </td>
                        </motion.tr>
                      ))}
                    </AnimatePresence>
                  </tbody>
                </table>
              </div>

              <div className="glass-panel" style={{ gridColumn: 'span 4', display: 'flex', flexDirection: 'column', gap: '20px' }}>
                <div className="panel-title"><ShieldAlert size={18} color="var(--success)" /> Federal Sync Status</div>
                <div style={{ background: 'rgba(52, 199, 89, 0.05)', padding: '16px', borderRadius: '8px', border: '1px solid rgba(52, 199, 89, 0.2)' }}>
                  <div style={{ color: 'var(--success)', fontWeight: '600', marginBottom: '8px', fontSize: '14px' }}>FINCEN API: CONNECTED</div>
                  <p style={{ fontSize: '13px', color: 'var(--text-secondary)', lineHeight: '1.5' }}>
                    All SAR files are successfully propagating to the federal Financial Crimes Enforcement Network.
                  </p>
                </div>
                
                <div className="panel-title mt-4">Automated Data Retention</div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', fontSize: '13px' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}><span>Total Records (Encrypted):</span> <span style={{ fontWeight: '600' }}>1.4 Million</span></div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}><span>Retention Cycle:</span> <span style={{ fontWeight: '600' }}>7 Years</span></div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}><span>Next Auto-Purge:</span> <span style={{ fontWeight: '600', color: 'var(--warning)' }}>Oct 12, 2026</span></div>
                </div>
              </div>
            </motion.div>
          ) : activeTab === 'file_complaint' ? (
            <motion.div 
              key="file_complaint"
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: -20 }}
              transition={{ duration: 0.4 }}
              style={{ width: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '80vh', padding: '20px' }}
            >
              <div className="glass-panel" style={{ width: '100%', maxWidth: '680px', display: 'flex', flexDirection: 'column', overflow: 'hidden', padding: '0', border: '1px solid rgba(0,240,255,0.2)', boxShadow: '0 0 40px rgba(0,0,0,0.4), 0 0 20px rgba(0,240,255,0.1)' }}>
                <div style={{ width: '100%', height: '360px', overflow: 'hidden', position: 'relative' }}>
                  <div style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, background: 'linear-gradient(to bottom, transparent 60%, rgba(13, 17, 23, 1) 100%)', zIndex: 1 }}></div>
                  <img src="/financial_fraud_trap.png" alt="Financial Fraud Trap" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                </div>
                <div style={{ padding: '0 40px 50px 40px', display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', position: 'relative', zIndex: 2, marginTop: '-40px', background: 'rgba(13, 17, 23, 1)' }}>
                  <h2 className="text-gradient" style={{ fontSize: '32px', fontWeight: '800', margin: '0 0 16px 0', letterSpacing: '2px', textShadow: '0 4px 20px rgba(0,240,255,0.2)' }}>FINANCIAL FRAUD</h2>
                  <p style={{ color: 'var(--text-secondary)', marginBottom: '36px', maxWidth: '420px', fontSize: '15px', lineHeight: '1.6' }}>If you suspect unauthorized access or have detected suspicious activity, file an immediate federal report.</p>
                  
                  <a href="https://cybercrime.gov.in/Webform/Accept.aspx" target="_blank" rel="noreferrer" style={{ textDecoration: 'none', width: '100%', maxWidth: '320px' }}>
                    <button style={{ width: '100%', background: 'linear-gradient(135deg, #ff3b30, #ff2b5e)', color: '#ffffff', border: '1px solid rgba(255,59,48,0.5)', borderRadius: '12px', padding: '16px', fontSize: '18px', fontWeight: '600', cursor: 'pointer', transition: 'all 0.3s', boxShadow: '0 8px 24px rgba(255,59,48,0.3)', textTransform: 'uppercase', letterSpacing: '1px', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px' }} onMouseOver={(e) => { e.currentTarget.style.transform = 'translateY(-3px)'; e.currentTarget.style.boxShadow = '0 12px 28px rgba(255,59,48,0.5)' }} onMouseOut={(e) => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = '0 8px 24px rgba(255,59,48,0.3)' }}>
                      <AlertTriangle size={20} /> Register Complaint
                    </button>
                  </a>
                </div>
              </div>
            </motion.div>
          ) : null}
        </AnimatePresence>
      </div>

      {/* Toast Notifications */}
      <div style={{ position: 'fixed', top: '20px', right: '20px', zIndex: 9999, display: 'flex', flexDirection: 'column', gap: '10px' }}>
        <AnimatePresence>
          {toasts.map(toast => (
            <motion.div
              key={toast.id}
              initial={{ opacity: 0, x: 50, scale: 0.9 }}
              animate={{ opacity: 1, x: 0, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              style={{
                background: toast.type === 'error' ? 'rgba(255, 59, 48, 0.9)' : 
                            toast.type === 'warning' ? 'rgba(255, 204, 0, 0.9)' : 
                            'rgba(52, 199, 89, 0.9)',
                color: 'white',
                padding: '12px 20px',
                borderRadius: '8px',
                boxShadow: '0 8px 32px rgba(0,0,0,0.3)',
                display: 'flex',
                alignItems: 'center',
                gap: '12px',
                fontWeight: '500',
                fontSize: '14px',
                backdropFilter: 'blur(10px)',
                border: '1px solid rgba(255,255,255,0.2)'
              }}
            >
              {toast.type === 'error' ? <AlertTriangle size={18} /> : 
               toast.type === 'warning' ? <ShieldAlert size={18} /> : 
               <CheckCircle size={18} />}
              {toast.message}
              <button 
                onClick={() => setToasts(prev => prev.filter(t => t.id !== toast.id))}
                style={{ background: 'transparent', border: 'none', color: 'white', cursor: 'pointer', marginLeft: 'auto', display: 'flex', alignItems: 'center' }}
              >
                <X size={14} />
              </button>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>
    </div>
    </>
  );
};

export default App;
